apiVersion: v1
kind: Pod
metadata: 
  name: webapp-2
  labels:
    name: webapp-2
    app: voting-app
spec:
  containers:
    - name: result-app-container
      image: dockersamples/examplevotingapp_result
      ports:
      - containerPort: 80