apiVersion: v1
kind: Pod
metadata: 
  name: webapp-1
  labels:
    name: webapp-1
    app: voting-app
spec:
  containers:
    - name: webapp-container
      image: dockersamples/examplevotingapp_vote
      ports:
      - containerPort: 80