apiVersion: v1
kind: Deployment
metadata:
   name: webapp-1-deployment
   labels:
     app: voting-app
spec:
   replicas: 1
   
   selector:
     matchLabels:
       name: webapp-1-pod
       app: voting-app

   template:
     metadata: 
      name: webapp-1-pod
      labels:
        name: webapp-1-pod
        app: voting-app
     spec:
      containers:
        - name: webapp-container
          image: dockersamples/examplevotingapp_vote
          ports:
          - containerPort: 80