apiVersion: v1
kind: Deployment
metadata:
   name: webapp-2-deployment
   labels:
     app: voting-app
spec:
   replicas: 1
   
   selector:
     matchLabels:
       name: webapp-2-pod
       app: voting-app

   template:
    metadata: 
      name: webapp-2-pod
      labels:
        name: webapp-2-pod
        app: voting-app
    spec:
      containers:
      - name: result-app-container
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80