apiVersion: v1
kind: Deployment
metadata:
   name: worker-app-deployment
   labels:
     app: voting-app
spec:
   replicas: 1
   
   selector:
     matchLabels:
       name: workerapp-pod
       app: voting-app

   template:
     metadata: 
      name: workerapp-pod
      labels:
        name: workerapp-pod
        app: voting-app
     spec:
      containers:
        - name: workerapp-container
          image: dockersamples/examplevotingapp_worker