apiVersion: v1
kind: Pod
metadata: 
  name: webapp-2-pod
  labels:
    name: webapp-2-pod
    app: voting-app
spec:
  containers:
    - name: result-app-container
      image: dockersamples/examplevotingapp_result
      ports:
      - containerPort: 80