apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: my-replica-set
  labels: 
    app: myapp 
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: tutum-helloworld
          image: tutum/hello-world
  replicas: 3
  selector: 
    matchLabels:
	  app: myapp
